image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1775.046429, 0.000000, 742.007764,
        0.000000, 1773.548622, 555.821789,
        0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.131017, 0.164824, -0.000016, 0.000031, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000,
        0.000000, 1.000000, 0.000000,
        0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [1743.885767, 0.000000, 742.634857, 0.000000,
        0.000000, 1754.117259, 556.130982, 0.000000,
        0.000000, 0.000000, 1.000000, 0.000000]